apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeworkz-audit
  namespace: kubeworkz-system
  labels:
    kubeworkz.io/app: kubeworkz-audit
spec:
  replicas: 1
  selector:
    matchLabels:
      kubeworkz.io/app: kubeworkz-audit
  template:
    metadata:
      labels:
        kubeworkz.io/app: kubeworkz-audit
    spec:
      containers:
        - name: kubeworkz-audit
          image: kubeorkz/kubeworkz:audit-0.0.1
          ports:
            - containerPort: 8888
      env:
        - name: JWT_SECRET
          value: 56F0D8DB90241C6E
