apiVersion: v1
kind: Service
metadata:
  name: kubeworkz-audit-nodeport
  namespace: kubeworkz-system
spec:
  type: NodePort
  selector:
    kubeworkz.io/app: kubeworkz-audit
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      nodePort: 30008