definitions:
  audit.EsResult:
    properties:
      events:
        items:
          $ref: '#/definitions/v1.Event'
        type: array
      total:
        type: integer
    type: object
  errcode.ErrorInfo:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  v1.Event:
    properties:
      apiAction:
        type: string
      apiVersion:
        type: string
      description:
        type: string
      errorCode:
        type: string
      errorMessage:
        type: string
      eventName:
        type: string
      eventTime:
        type: integer
      eventType:
        type: string
      eventVersion:
        type: string
      requestId:
        type: string
      requestMethod:
        type: string
      requestParameters:
        type: string
      resourceList:
        items:
          $ref: '#/definitions/v1.ResourceData'
        type: array
      responseElements:
        type: string
      responseStatus:
        type: integer
      sourceIpAddress:
        type: string
      url:
        type: string
      userAgent:
        type: string
      userIdentity:
        $ref: '#/definitions/v1.UserIdentity'
    type: object
  v1.ResourceData:
    properties:
      resourceId:
        type: string
      resourceName:
        type: string
      resourceType:
        type: string
    type: object
  v1.UserIdentity:
    properties:
      accountId:
        type: string
    type: object
info:
  contact: {}
  description: This is KubeWorkz-Audit api documentation.
  title: Swagger KubeWorkz-Audit API
  version: "1.0"
paths:
  /api/v1/kube/audit:
    get:
      description: query audit log from es
      parameters:
      - in: query
        name: endTime
        type: integer
      - in: query
        name: eventName
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: resourceName
        type: string
      - in: query
        name: responseStatus
        type: integer
      - in: query
        name: size
        type: integer
      - in: query
        name: sourceIpAddress
        type: string
      - in: query
        name: startTime
        type: integer
      - in: query
        name: userName
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/audit.EsResult'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errcode.ErrorInfo'
      summary: query audit log
      tags:
      - audit
  /api/v1/kube/audit/export:
    get:
      description: query and export audit log from es
      parameters:
      - in: query
        name: endTime
        type: integer
      - in: query
        name: eventName
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: resourceName
        type: string
      - in: query
        name: responseStatus
        type: integer
      - in: query
        name: size
        type: integer
      - in: query
        name: sourceIpAddress
        type: string
      - in: query
        name: startTime
        type: integer
      - in: query
        name: userName
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errcode.ErrorInfo'
      summary: export audit log
      tags:
      - audit
  /api/v1/kube/healthz:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"msg": "hello"}'
          schema:
            type: string
      summary: health check
swagger: "2.0"
